// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRFlbf9Jrf0iuuD35BV57gAbhJpW6TNy0',
    appId: '1:285971971611:web:2e9df9c30c807b7b10c2be',
    messagingSenderId: '285971971611',
    projectId: 'judoseclin-e4b0f',
    authDomain: 'judoseclin-e4b0f.firebaseapp.com',
    storageBucket: 'judoseclin-e4b0f.appspot.com',
    measurementId: 'G-GYDBM9MM75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs3uGWEsH4IsnCS5n2wW8XDH4WOSZCQgs',
    appId: '1:285971971611:android:843c6c7d8c1c2f4110c2be',
    messagingSenderId: '285971971611',
    projectId: 'judoseclin-e4b0f',
    storageBucket: 'judoseclin-e4b0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrYp5jlPSCH_YWtesZ5UaMIdhYLoSAXRY',
    appId: '1:285971971611:ios:e6818d7e1c0a568010c2be',
    messagingSenderId: '285971971611',
    projectId: 'judoseclin-e4b0f',
    storageBucket: 'judoseclin-e4b0f.appspot.com',
    iosClientId:
        '285971971611-1c2u3fnd5orf8edpm7hles4u3neeqgrf.apps.googleusercontent.com',
    iosBundleId: 'fr.benoitfontaine.judoseclin',
  );
}
