services:
  judoseclin:
    build: .
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:80/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
