name: judoseclin
description: "Cette application vous permet de suivre l'actualité du club mais aussi de gérer vos inscriptions aux compétitions"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+18

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.3"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freelance: ^1.0.2
  flutter_markdown: ^0.7.3
  carousel_slider: ^5.0.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  freezed: ^2.5.2
  flutter_hooks: ^0.20.5
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3
  cloud_firestore: ^5.2.1
  http: ^1.2.2
  url_launcher: ^6.3.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_spinkit: ^5.2.1
  intl: ^0.19.0
  go_router: ^14.2.3
  injectable: ^2.4.4
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/markdown/
    - assets/documents/
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: fonts/MaterialIcons-Regular.otf
    - family: Hiromisake
      fonts:
        - asset: fonts/Hiromisake-Regular.ttf