name: judoseclin
description: "Cette application vous permet de suivre l'actualité du club mais aussi de gérer vos inscriptions aux compétitions"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+18

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.7.3
  carousel_slider: ^5.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  freezed: ^3.1.0
  flutter_hooks: ^0.21.2
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.1
  cloud_firestore: ^6.0.1
  http: ^1.3.0
  url_launcher: ^6.3.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_spinkit: ^5.2.1
  intl: ^0.20.2
  go_router: ^16.2.1
  injectable: ^2.4.4
  get_it: ^8.0.3
  cloud_functions: ^6.0.1
  provider: ^6.1.2
  pdf: ^3.11.3
  universal_html: ^2.2.4
  printing: ^5.14.2
  web: ^1.1.1
  js: ^0.7.2
  path_provider: ^2.1.5
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/markdown/
    - assets/documents/
    - assets/emojis/
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/font/MaterialIcons-Regular.ttf
    - family: Hiromisake
      fonts:
        - asset: fonts/Hiromisake-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: NotoEmoji
      fonts:
        - asset: assets/fonts/NotoEmoji-Regular.ttf

